version: '3'
services:

  # TPM simulator
  tpmsim:
    image: fraunhoferaisec/tpmsim:develop
    build:
      context: .
    volumes:
      # Always extract a "clean state" for our TPM simulator to prevent DA lockout issues
      - ./tpmsim_data.tar:/tpmsim_data.tar
    ports:
      - "9505:9505"

